const HANGUL_CONSONANTS = [
  { char: "ㄱ", romanization: "g/k", sound: "like 'g' in go" },
  { char: "ㄴ", romanization: "n",   sound: "like 'n' in no" },
  { char: "ㄷ", romanization: "d/t", sound: "like 'd' in do" },
  { char: "ㄹ", romanization: "r/l", sound: "between 'r' and 'l'" },
  { char: "ㅁ", romanization: "m",   sound: "like 'm' in me" },
  { char: "ㅂ", romanization: "b/p", sound: "like 'b' in boy" },
  { char: "ㅅ", romanization: "s",   sound: "like 's' in sun" },
  { char: "ㅇ", romanization: "ng/silent", sound: "silent at start, 'ng' at end" },
  { char: "ㅈ", romanization: "j",   sound: "like 'j' in joy" },
  { char: "ㅊ", romanization: "ch",  sound: "like 'ch' in chair" },
  { char: "ㅋ", romanization: "k",   sound: "aspirated 'k'" },
  { char: "ㅌ", romanization: "t",   sound: "aspirated 't'" },
  { char: "ㅍ", romanization: "p",   sound: "aspirated 'p'" },
  { char: "ㅎ", romanization: "h",   sound: "like 'h' in hat" },
];

const HANGUL_VOWELS = [
  { char: "ㅏ", romanization: "a",   sound: "like 'a' in father" },
  { char: "ㅑ", romanization: "ya",  sound: "like 'ya' in yard" },
  { char: "ㅓ", romanization: "eo",  sound: "like 'u' in fun" },
  { char: "ㅕ", romanization: "yeo", sound: "like 'yuh'" },
  { char: "ㅗ", romanization: "o",   sound: "like 'o' in old" },
  { char: "ㅛ", romanization: "yo",  sound: "like 'yo' in yoga" },
  { char: "ㅜ", romanization: "u",   sound: "like 'oo' in food" },
  { char: "ㅠ", romanization: "yu",  sound: "like 'yu' in you" },
  { char: "ㅡ", romanization: "eu",  sound: "no English equivalent" },
  { char: "ㅣ", romanization: "i",   sound: "like 'ee' in see" },
];

const VOCABULARY = [
  // ── Greetings ──────────────────────────────────────────────────────────────
  { korean: "안녕하세요",  romanization: "annyeonghaseyo",  english: "Hello (formal)",        category: "Greetings" },
  { korean: "안녕",       romanization: "annyeong",        english: "Hi / Bye (informal)",   category: "Greetings" },
  { korean: "감사합니다", romanization: "gamsahamnida",    english: "Thank you (formal)",     category: "Greetings" },
  { korean: "고마워요",   romanization: "gomawoyo",        english: "Thank you (casual)",     category: "Greetings" },
  { korean: "죄송합니다", romanization: "joesonghamnida",  english: "I'm sorry (formal)",     category: "Greetings" },
  { korean: "괜찮아요",   romanization: "gwaenchanayo",    english: "It's okay / I'm fine",   category: "Greetings" },
  { korean: "네",         romanization: "ne",              english: "Yes",                    category: "Greetings" },
  { korean: "아니요",     romanization: "aniyo",           english: "No",                     category: "Greetings" },
  { korean: "안녕히 가세요", romanization: "annyeonghi gaseyo", english: "Goodbye (to one leaving)", category: "Greetings" },
  { korean: "만나서 반가워요", romanization: "mannaseo bangawoyo", english: "Nice to meet you", category: "Greetings" },
  { korean: "잘 지내요?", romanization: "jal jinaeyo",    english: "How are you?",            category: "Greetings" },
  { korean: "잘 지내요",  romanization: "jal jinaeyo",    english: "I'm doing well",          category: "Greetings" },

  // ── People ─────────────────────────────────────────────────────────────────
  { korean: "나",    romanization: "na",       english: "I / Me (informal)", category: "People" },
  { korean: "저",    romanization: "jeo",      english: "I / Me (formal)",   category: "People" },
  { korean: "우리",  romanization: "uri",      english: "We / Our",          category: "People" },
  { korean: "친구",  romanization: "chingu",   english: "Friend",            category: "People" },
  { korean: "가족",  romanization: "gajok",    english: "Family",            category: "People" },
  { korean: "엄마",  romanization: "eomma",    english: "Mom",               category: "People" },
  { korean: "아빠",  romanization: "appa",     english: "Dad",               category: "People" },
  { korean: "오빠",  romanization: "oppa",     english: "Older brother (female speaker)", category: "People" },
  { korean: "언니",  romanization: "eonni",    english: "Older sister (female speaker)",  category: "People" },
  { korean: "형",    romanization: "hyeong",   english: "Older brother (male speaker)",   category: "People" },
  { korean: "누나",  romanization: "nuna",     english: "Older sister (male speaker)",    category: "People" },
  { korean: "선생님", romanization: "seonsaengnim", english: "Teacher",       category: "People" },
  { korean: "학생",  romanization: "haksaeng", english: "Student",           category: "People" },

  // ── Numbers ────────────────────────────────────────────────────────────────
  { korean: "일",   romanization: "il",    english: "1 (Sino-Korean)",    category: "Numbers" },
  { korean: "이",   romanization: "i",     english: "2 (Sino-Korean)",    category: "Numbers" },
  { korean: "삼",   romanization: "sam",   english: "3 (Sino-Korean)",    category: "Numbers" },
  { korean: "사",   romanization: "sa",    english: "4 (Sino-Korean)",    category: "Numbers" },
  { korean: "오",   romanization: "o",     english: "5 (Sino-Korean)",    category: "Numbers" },
  { korean: "육",   romanization: "yuk",   english: "6 (Sino-Korean)",    category: "Numbers" },
  { korean: "칠",   romanization: "chil",  english: "7 (Sino-Korean)",    category: "Numbers" },
  { korean: "팔",   romanization: "pal",   english: "8 (Sino-Korean)",    category: "Numbers" },
  { korean: "구",   romanization: "gu",    english: "9 (Sino-Korean)",    category: "Numbers" },
  { korean: "십",   romanization: "sip",   english: "10 (Sino-Korean)",   category: "Numbers" },
  { korean: "하나", romanization: "hana",  english: "1 (Native Korean)",  category: "Numbers" },
  { korean: "둘",   romanization: "dul",   english: "2 (Native Korean)",  category: "Numbers" },
  { korean: "셋",   romanization: "set",   english: "3 (Native Korean)",  category: "Numbers" },
  { korean: "넷",   romanization: "net",   english: "4 (Native Korean)",  category: "Numbers" },
  { korean: "다섯", romanization: "daseot", english: "5 (Native Korean)", category: "Numbers" },

  // ── Food & Drink ───────────────────────────────────────────────────────────
  { korean: "물",     romanization: "mul",       english: "Water",               category: "Food" },
  { korean: "밥",     romanization: "bap",       english: "Rice / Meal",         category: "Food" },
  { korean: "빵",     romanization: "ppang",     english: "Bread",               category: "Food" },
  { korean: "고기",   romanization: "gogi",      english: "Meat",                category: "Food" },
  { korean: "생선",   romanization: "saengseon", english: "Fish",                category: "Food" },
  { korean: "채소",   romanization: "chaeso",    english: "Vegetables",          category: "Food" },
  { korean: "과일",   romanization: "gwail",     english: "Fruit",               category: "Food" },
  { korean: "김치",   romanization: "gimchi",    english: "Kimchi",              category: "Food" },
  { korean: "불고기", romanization: "bulgogi",   english: "Bulgogi",             category: "Food" },
  { korean: "비빔밥", romanization: "bibimbap",  english: "Bibimbap",            category: "Food" },
  { korean: "떡볶이", romanization: "tteokbokki", english: "Spicy rice cakes",  category: "Food" },
  { korean: "커피",   romanization: "keopi",     english: "Coffee",              category: "Food" },
  { korean: "차",     romanization: "cha",       english: "Tea",                 category: "Food" },
  { korean: "주스",   romanization: "juseu",     english: "Juice",               category: "Food" },
  { korean: "맛있어요", romanization: "massisseoyo", english: "It's delicious",  category: "Food" },
  { korean: "맛없어요", romanization: "maseopseoyo", english: "It's not tasty",  category: "Food" },

  // ── Places ─────────────────────────────────────────────────────────────────
  { korean: "학교",   romanization: "hakgyo",     english: "School",       category: "Places" },
  { korean: "집",     romanization: "jip",        english: "House / Home", category: "Places" },
  { korean: "식당",   romanization: "sikdang",    english: "Restaurant",   category: "Places" },
  { korean: "병원",   romanization: "byeongwon",  english: "Hospital",     category: "Places" },
  { korean: "은행",   romanization: "eunhaeng",   english: "Bank",         category: "Places" },
  { korean: "편의점", romanization: "pyeonuijeom", english: "Convenience store", category: "Places" },
  { korean: "공항",   romanization: "gonghang",   english: "Airport",      category: "Places" },
  { korean: "지하철역", romanization: "jihacheol yeok", english: "Subway station", category: "Places" },
  { korean: "공원",   romanization: "gongwon",    english: "Park",         category: "Places" },
  { korean: "서울",   romanization: "seoul",      english: "Seoul",        category: "Places" },

  // ── Verbs ──────────────────────────────────────────────────────────────────
  { korean: "가다",    romanization: "gada",      english: "To go",         category: "Verbs" },
  { korean: "오다",    romanization: "oda",       english: "To come",       category: "Verbs" },
  { korean: "먹다",    romanization: "meokda",    english: "To eat",        category: "Verbs" },
  { korean: "마시다",  romanization: "masida",    english: "To drink",      category: "Verbs" },
  { korean: "자다",    romanization: "jada",      english: "To sleep",      category: "Verbs" },
  { korean: "일어나다", romanization: "ireonada", english: "To wake up",    category: "Verbs" },
  { korean: "공부하다", romanization: "gongbuhada", english: "To study",    category: "Verbs" },
  { korean: "일하다",  romanization: "ilhada",    english: "To work",       category: "Verbs" },
  { korean: "보다",    romanization: "boda",      english: "To see / watch", category: "Verbs" },
  { korean: "듣다",    romanization: "deutda",    english: "To listen",     category: "Verbs" },
  { korean: "말하다",  romanization: "malhada",   english: "To speak",      category: "Verbs" },
  { korean: "읽다",    romanization: "ikda",      english: "To read",       category: "Verbs" },
  { korean: "쓰다",    romanization: "sseuda",    english: "To write",      category: "Verbs" },
  { korean: "사다",    romanization: "sada",      english: "To buy",        category: "Verbs" },
  { korean: "만나다",  romanization: "mannada",   english: "To meet",       category: "Verbs" },
  { korean: "알다",    romanization: "alda",      english: "To know",       category: "Verbs" },
  { korean: "좋아하다", romanization: "joahada",  english: "To like",       category: "Verbs" },
  { korean: "사랑하다", romanization: "saranghada", english: "To love",     category: "Verbs" },
  { korean: "있다",    romanization: "itda",      english: "To have / exist", category: "Verbs" },
  { korean: "없다",    romanization: "eopda",     english: "To not have / not exist", category: "Verbs" },

  // ── Adjectives ─────────────────────────────────────────────────────────────
  { korean: "크다",     romanization: "keuda",      english: "Big / Large",      category: "Adjectives" },
  { korean: "작다",     romanization: "jakda",      english: "Small / Little",   category: "Adjectives" },
  { korean: "많다",     romanization: "manta",      english: "Many / A lot",     category: "Adjectives" },
  { korean: "적다",     romanization: "jeokda",     english: "Few / Little",     category: "Adjectives" },
  { korean: "좋다",     romanization: "jota",       english: "Good",             category: "Adjectives" },
  { korean: "나쁘다",   romanization: "nappeuda",   english: "Bad",              category: "Adjectives" },
  { korean: "빠르다",   romanization: "ppareuda",   english: "Fast",             category: "Adjectives" },
  { korean: "느리다",   romanization: "neurida",    english: "Slow",             category: "Adjectives" },
  { korean: "예쁘다",   romanization: "yeppeuda",   english: "Pretty / Beautiful", category: "Adjectives" },
  { korean: "멋있다",   romanization: "meositda",   english: "Cool / Stylish",   category: "Adjectives" },
  { korean: "재미있다", romanization: "jaemiitda",  english: "Interesting / Fun", category: "Adjectives" },
  { korean: "어렵다",   romanization: "eoryeopda",  english: "Difficult",        category: "Adjectives" },
  { korean: "쉽다",     romanization: "swipda",     english: "Easy",             category: "Adjectives" },
  { korean: "덥다",     romanization: "deobda",     english: "Hot (weather)",    category: "Adjectives" },
  { korean: "춥다",     romanization: "chupda",     english: "Cold (weather)",   category: "Adjectives" },

  // ── Time ───────────────────────────────────────────────────────────────────
  { korean: "오늘",  romanization: "oneul",   english: "Today",      category: "Time" },
  { korean: "내일",  romanization: "naeil",   english: "Tomorrow",   category: "Time" },
  { korean: "어제",  romanization: "eoje",    english: "Yesterday",  category: "Time" },
  { korean: "지금",  romanization: "jigeum",  english: "Now",        category: "Time" },
  { korean: "아침",  romanization: "achim",   english: "Morning",    category: "Time" },
  { korean: "점심",  romanization: "jeomsim", english: "Lunch / Noon", category: "Time" },
  { korean: "저녁",  romanization: "jeonyeok", english: "Evening",   category: "Time" },
  { korean: "밤",    romanization: "bam",     english: "Night",      category: "Time" },
  { korean: "월요일", romanization: "woryoil", english: "Monday",    category: "Time" },
  { korean: "화요일", romanization: "hwayoil", english: "Tuesday",   category: "Time" },
  { korean: "수요일", romanization: "suyoil",  english: "Wednesday", category: "Time" },
  { korean: "목요일", romanization: "mogyoil", english: "Thursday",  category: "Time" },
  { korean: "금요일", romanization: "geumyoil", english: "Friday",   category: "Time" },
  { korean: "토요일", romanization: "toyoil",  english: "Saturday",  category: "Time" },
  { korean: "일요일", romanization: "iryoil",  english: "Sunday",    category: "Time" },

  // ── Colors ─────────────────────────────────────────────────────────────────
  { korean: "빨간색", romanization: "ppalgansaek", english: "Red",    category: "Colors" },
  { korean: "파란색", romanization: "paransaek",   english: "Blue",   category: "Colors" },
  { korean: "초록색", romanization: "choroksaek",  english: "Green",  category: "Colors" },
  { korean: "노란색", romanization: "noransaek",   english: "Yellow", category: "Colors" },
  { korean: "흰색",   romanization: "huinsaek",    english: "White",  category: "Colors" },
  { korean: "검은색", romanization: "geomeunsaek", english: "Black",  category: "Colors" },
  { korean: "보라색", romanization: "borasaek",    english: "Purple", category: "Colors" },
  { korean: "주황색", romanization: "juhwangsaek", english: "Orange", category: "Colors" },
  { korean: "분홍색", romanization: "bunhongsaek", english: "Pink",   category: "Colors" },
  { korean: "갈색",   romanization: "galsaek",     english: "Brown",  category: "Colors" },

  // ── Emotions ───────────────────────────────────────────────────────────────
  { korean: "행복해요",  romanization: "haengbokhaeyo", english: "Happy",     category: "Emotions" },
  { korean: "슬퍼요",   romanization: "seulpeoyo",     english: "Sad",       category: "Emotions" },
  { korean: "화나요",   romanization: "hwanayo",       english: "Angry",     category: "Emotions" },
  { korean: "무서워요", romanization: "museowoyo",     english: "Scared",    category: "Emotions" },
  { korean: "피곤해요", romanization: "pigonhaeyo",    english: "Tired",     category: "Emotions" },
  { korean: "배고파요", romanization: "baegopayo",     english: "Hungry",    category: "Emotions" },
  { korean: "배불러요", romanization: "baebulleoyo",   english: "Full (after eating)", category: "Emotions" },
  { korean: "심심해요", romanization: "simsimhaeyo",   english: "Bored",     category: "Emotions" },
  { korean: "신나요",   romanization: "sinnayo",       english: "Excited",   category: "Emotions" },
  { korean: "걱정돼요", romanization: "geokjeongdwaeyo", english: "Worried", category: "Emotions" },
];

// ── Sentence Patterns ────────────────────────────────────────────────────────
const SENTENCE_PATTERNS = [
  {
    id: "sov",
    title: "Word Order: SOV",
    badge: "Core Rule",
    badgeColor: "#6c63ff",
    summary: "Korean sentences follow Subject → Object → Verb order. The verb always comes last.",
    explanation: "In English you say 'I eat rice.' In Korean the verb 먹어요 (eat) comes at the end: 나는 밥을 먹어요. This applies to all Korean sentences — the verb is always the final element.",
    examples: [
      { korean: "나는 밥을 먹어요",     romanization: "naneun babeul meogeoyo",   english: "I eat rice",          parts: ["나는·I (topic)", "밥을·rice (object)", "먹어요·eat"] },
      { korean: "저는 물을 마셔요",     romanization: "jeoneun mureul mashyeoyo", english: "I drink water",       parts: ["저는·I (topic)", "물을·water (object)", "마셔요·drink"] },
      { korean: "친구는 음악을 들어요", romanization: "chinguneun eumageul deureoyo", english: "My friend listens to music", parts: ["친구는·friend (topic)", "음악을·music (object)", "들어요·listens"] },
    ],
  },
  {
    id: "topic",
    title: "Topic Particle 은/는",
    badge: "Particles",
    badgeColor: "#ff6584",
    summary: "은 (after consonant) / 는 (after vowel) marks what the sentence is about.",
    explanation: "The topic particle tells the listener what you're talking about. Use 은 when the preceding syllable ends in a consonant, and 는 when it ends in a vowel. Topics are often things already known in the conversation.",
    examples: [
      { korean: "저는 학생이에요",   romanization: "jeoneun haksaengieyo",  english: "I am a student",     parts: ["저는·I (topic)", "학생이에요·am a student"] },
      { korean: "오늘은 더워요",    romanization: "oneureun deowoyo",      english: "Today is hot",        parts: ["오늘은·today (topic)", "더워요·is hot"] },
      { korean: "이 책은 재미있어요", romanization: "i chaegeun jaemiisseoyo", english: "This book is interesting", parts: ["이 책은·this book (topic)", "재미있어요·is interesting"] },
    ],
  },
  {
    id: "subject",
    title: "Subject Particle 이/가",
    badge: "Particles",
    badgeColor: "#ff6584",
    summary: "이 (after consonant) / 가 (after vowel) marks the grammatical subject — often new information.",
    explanation: "While 은/는 marks the topic (what you're talking about), 이/가 marks the subject (who/what performs the action). It often introduces new information or emphasizes the subject. Use 이 after a consonant, 가 after a vowel.",
    examples: [
      { korean: "비가 와요",        romanization: "biga wayo",         english: "Rain is coming / It's raining", parts: ["비가·rain (subject)", "와요·comes"] },
      { korean: "친구가 전화했어요", romanization: "chinguga jeonhwahaesseoyo", english: "My friend called",  parts: ["친구가·friend (subject)", "전화했어요·called"] },
      { korean: "고양이가 자요",    romanization: "goyangi ga jayo",   english: "The cat is sleeping",  parts: ["고양이가·cat (subject)", "자요·sleeps"] },
    ],
  },
  {
    id: "object",
    title: "Object Particle 을/를",
    badge: "Particles",
    badgeColor: "#ff6584",
    summary: "을 (after consonant) / 를 (after vowel) marks the direct object of a verb.",
    explanation: "This particle attaches to the noun receiving the action. Use 을 when the noun ends in a consonant, and 를 when it ends in a vowel. The object always comes before the verb.",
    examples: [
      { korean: "사과를 먹어요",   romanization: "sagwareul meogeoyo",  english: "I eat an apple",      parts: ["사과를·apple (object)", "먹어요·eat"] },
      { korean: "한국어를 공부해요", romanization: "hangugeo reul gongbuhaeyo", english: "I study Korean", parts: ["한국어를·Korean (object)", "공부해요·study"] },
      { korean: "음악을 들어요",   romanization: "eumageul deureoyo",  english: "I listen to music",   parts: ["음악을·music (object)", "들어요·listen"] },
    ],
  },
  {
    id: "location",
    title: "Location: 에 vs 에서",
    badge: "Particles",
    badgeColor: "#ff6584",
    summary: "에 = static location or direction. 에서 = location of an action.",
    explanation: "에 is used for where something exists (있어요/없어요) or where you're going (direction). 에서 is used for where an action takes place. Think of 에 as 'at/to' and 에서 as 'at (doing something here)' or 'from'.",
    examples: [
      { korean: "학교에 가요",    romanization: "hakgyoe gayo",      english: "I go to school",        parts: ["학교에·to school", "가요·go"] },
      { korean: "집에 있어요",   romanization: "jibe isseoyo",      english: "I am at home",          parts: ["집에·at home", "있어요·am/exist"] },
      { korean: "카페에서 공부해요", romanization: "kapeeseo gongbuhaeyo", english: "I study at the café", parts: ["카페에서·at the café", "공부해요·study"] },
    ],
  },
  {
    id: "negation",
    title: "Negation with 안",
    badge: "Grammar",
    badgeColor: "#43e97b",
    summary: "Place 안 directly before the verb to make it negative.",
    explanation: "안 is the simple negation adverb meaning 'not'. Put it right before the verb or adjective. For compound verbs ending in 하다 (to do), insert 안 before 하다: 공부 안 해요. This is the everyday spoken negation.",
    examples: [
      { korean: "안 먹어요",       romanization: "an meogeoyo",        english: "I don't eat",          parts: ["안·not", "먹어요·eat"] },
      { korean: "안 가요",        romanization: "an gayo",            english: "I'm not going",        parts: ["안·not", "가요·go"] },
      { korean: "공부 안 해요",   romanization: "gongbu an haeyo",    english: "I don't study",        parts: ["공부·study", "안·not", "해요·do"] },
    ],
  },
  {
    id: "tobe",
    title: "To Be: 이에요/예요",
    badge: "Grammar",
    badgeColor: "#43e97b",
    summary: "이에요 (after consonant) / 예요 (after vowel) = 'am/is/are' for identification.",
    explanation: "To say someone IS something (a noun), attach 이에요 to nouns ending in a consonant, or 예요 to nouns ending in a vowel. This is different from 있어요 which means to exist or have. For negative: noun + 이/가 아니에요 (is not).",
    examples: [
      { korean: "저는 학생이에요",  romanization: "jeoneun haksaengieyo",  english: "I am a student",     parts: ["저는·I (topic)", "학생이에요·am a student"] },
      { korean: "이거 뭐예요?",    romanization: "igeo mwoyeyo",         english: "What is this?",       parts: ["이거·this", "뭐예요?·what is?"] },
      { korean: "저는 선생님이 아니에요", romanization: "jeoneun seonsaengnimi anieyo", english: "I'm not a teacher", parts: ["저는·I", "선생님이·teacher", "아니에요·am not"] },
    ],
  },
  {
    id: "polite",
    title: "Polite Endings: 아요/어요",
    badge: "Verbs",
    badgeColor: "#ffa94d",
    summary: "Most verbs in polite speech end in 아요 or 어요 — the everyday standard form.",
    explanation: "Remove 다 from the dictionary form, then add 아요 if the last vowel is ㅏ or ㅗ, or 어요 for all others. 하다 verbs become 해요. This is the polite informal level you'll use most of the time.",
    examples: [
      { korean: "가요",    romanization: "gayo",     english: "go (polite)",    parts: ["가다 → 가·stem", "요·polite ending"] },
      { korean: "먹어요",  romanization: "meogeoyo", english: "eat (polite)",   parts: ["먹다 → 먹·stem", "어요·polite ending"] },
      { korean: "공부해요", romanization: "gongbuhaeyo", english: "study (polite)", parts: ["공부하다 → 공부·stem", "해요·do (polite)"] },
    ],
  },
  {
    id: "question",
    title: "Asking Questions",
    badge: "Grammar",
    badgeColor: "#43e97b",
    summary: "Korean questions use the same word order as statements — just change your intonation or add a question word.",
    explanation: "You can make any statement a yes/no question just by raising your voice at the end. Question words (뭐=what, 어디=where, 언제=when, 누구=who, 왜=why, 어떻게=how) slot into the sentence where the answer would go. The verb still comes last.",
    examples: [
      { korean: "밥을 먹어요?",    romanization: "babeul meogeoyo?",   english: "Do you eat rice?",     parts: ["밥을·rice (object)", "먹어요?·eat? (rising intonation)"] },
      { korean: "뭐를 먹어요?",   romanization: "mworeul meogeoyo?",  english: "What do you eat?",     parts: ["뭐를·what (object)", "먹어요?·eat?"] },
      { korean: "어디에 가요?",   romanization: "eodie gayo?",        english: "Where are you going?",  parts: ["어디에·where (to)", "가요?·go?"] },
    ],
  },
  {
    id: "past",
    title: "Past Tense: 았어요/었어요",
    badge: "Verbs",
    badgeColor: "#ffa94d",
    summary: "Add 았어요 (after ㅏ/ㅗ vowels) or 었어요 (all others) to the verb stem for past tense.",
    explanation: "Past tense in Korean is formed by taking the verb stem and adding 았어요 or 었어요. The rule is the same as 아요/어요 — ㅏ or ㅗ takes 았, everything else takes 었. 하다 becomes 했어요.",
    examples: [
      { korean: "먹었어요",    romanization: "meogeosseoyo",  english: "I ate",         parts: ["먹·stem", "었어요·past tense ending"] },
      { korean: "갔어요",     romanization: "gasseoyo",      english: "I went",        parts: ["가·stem", "았어요·past tense ending"] },
      { korean: "공부했어요",  romanization: "gongbuhaesseoyo", english: "I studied",  parts: ["공부하·stem", "았어요 → 했어요·past"] },
    ],
  },
];

// ── Sentence Builder Exercises ────────────────────────────────────────────────
const SENTENCE_BUILDER = [
  { english: "I eat rice",             words: ["나는", "밥을", "먹어요"],              pattern: "sov" },
  { english: "I drink water",          words: ["저는", "물을", "마셔요"],              pattern: "sov" },
  { english: "I go to school",         words: ["저는", "학교에", "가요"],             pattern: "location" },
  { english: "I study at home",        words: ["저는", "집에서", "공부해요"],         pattern: "location" },
  { english: "I am a student",         words: ["저는", "학생이에요"],                 pattern: "tobe" },
  { english: "I don't eat",            words: ["저는", "안", "먹어요"],               pattern: "negation" },
  { english: "I don't go",             words: ["저는", "안", "가요"],                 pattern: "negation" },
  { english: "I listen to music",      words: ["저는", "음악을", "들어요"],           pattern: "object" },
  { english: "Where are you going?",   words: ["어디에", "가요?"],                    pattern: "question" },
  { english: "What do you eat?",       words: ["뭐를", "먹어요?"],                    pattern: "question" },
  { english: "I studied Korean",       words: ["저는", "한국어를", "공부했어요"],     pattern: "past" },
  { english: "I ate rice",             words: ["저는", "밥을", "먹었어요"],           pattern: "past" },
  { english: "My friend is coming",    words: ["친구가", "와요"],                     pattern: "subject" },
  { english: "It is raining",          words: ["비가", "와요"],                       pattern: "subject" },
  { english: "I like Korean food",     words: ["저는", "한국 음식을", "좋아해요"],    pattern: "object" },
  { english: "Today is hot",           words: ["오늘은", "더워요"],                   pattern: "topic" },
  { english: "I went to the hospital", words: ["저는", "병원에", "갔어요"],           pattern: "past" },
  { english: "I don't study",          words: ["공부", "안", "해요"],                 pattern: "negation" },
];
